version: '2'

services:
  pre-commit:
    image: docker-pre-commit:localbuild
    build: .
    volumes:
      - .:/opt/repo
      - pre-commit-cache:/root/.cache/pre-commit

volumes:
  pre-commit-cache:

